In [5]:
import numpy as np
k=np.array([[1,2,3],[4,5,6]])
print(k)

[[1 2 3]
 [4 5 6]]


In [6]:
for i in np.nditer(k):
    print(i)

1
2
3
4
5
6


In [12]:
vnew=np.vsplit(k,1)
print(vnew)

[array([[1, 2, 3],
       [4, 5, 6]])]


In [10]:
print("sqrt",np.sqrt(k))#sqrt of array

sqrt [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [13]:
print("exp",np.exp(k))#exp of array

exp [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [14]:
print("sin",np.sin(k))#sin of array

sin [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [15]:
print("cos",np.cos(k))#cos of array

cos [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [16]:
print(k.sum())#sum

21


In [29]:
v=[[6,5],[7,8]]#multiplication
p=[[9,7],[7,2]]
s=np.dot(v,p)
print(s)

[[ 89  52]
 [119  65]]


In [31]:
v=[[6,5],[7,8]]#addition for tow array
p=[[9,7],[7,2]]
s=np.add(v,p)
print(s)

[[15 12]
 [14 10]]


In [35]:
sliced_arr=v[:1] #array slicing
print(sliced_arr)

[[6, 5]]


In [36]:
print("all() with axis none",np.all(bool))
print("all() with axis 0",np.all(bool,axis=0))#any()

all() with axis none <class 'bool'>
all() with axis 0 <class 'bool'>


In [43]:
temp=np.arange(8)#reshape to 2 row and 4 column
print(temp)
re=temp.reshape(2,4)
print(re)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [45]:
print("Maximum is",temp.max()) #max number find

Maximum is 7


In [53]:
merg=np.vstack((v,p)) #merging two array verticallly
print("Vertical",merg)
merg=np.hstack((v,p)) #merging two array horizontally
print("horizontal",merg)

Vertical [[6 5]
 [7 8]
 [9 7]
 [7 2]]
horizontal [[6 5 9 7]
 [7 8 7 2]]


In [48]:
print("minimun is",temp.min())#minimun number find 

minimun is 0


In [55]:
print("standerd deviation",np.std(v))#standard deviation

standerd deviation 1.118033988749895


In [58]:
print("shape a:{}".format(k.shape))#shape of array



shape a:(2, 3)


In [59]:
print("ndim {}".format(k.ndim))#diamentions of array

ndim 2


In [60]:
print("size {}".format(k.size))#size of aaray

size 6


In [62]:
print(f"dtype {k.dtype}")#data type of array
print(f"itemsize {k.itemsize}")#item size of array
print(f"data {k.data}")

dtype int64
itemsize 8
data <memory at 0x7f726c1b7ba0>
